name: Nightly

on:
  schedule:
    # Trigger a build everyday to capture rustc change early
    # This runs at 01:53 UTC, a randomly generated time after
    # daily nightly release.
    - cron: '53 1 * * *'
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'nightly'
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose
